name: hoomd-organics
channels:
  - conda-forge
dependencies:
  - boltons
  - foyer
  - freud
  - gsd>=3.0
  - hoomd=4.1=*gpu*
  - mbuild
  - numpy
  - openbabel
  - pip
  - py3Dmol
  - pytest
  - pytest-cov
  - python=3.9
  - unyt
  - symengine
  - python-symengine
  - sympy
  - pip:
      - git+https://github.com/mosdef-hub/gmso.git@main
      - git+https://github.com/cmelab/cmeutils.git@master
      - git+https://github.com/cmelab/grits.git@main
