name: flowermd-dev
channels:
  - conda-forge
dependencies:
  - foyer >=0.12.0
  - fresnel
  - freud >=3.0
  - gmso >=0.12.0
  - gsd >=3.0
  - grits >=0.5.0
  - hoomd >=4.5, <5.0
  - mbuild >=0.17.0
  - numpy <2.0
  - openbabel >=3
  - pytorch
  - pip
  - pre-commit
  - py3Dmol
  - pytest
  - pytest-cov
  - nbmake
  - python >=3.10, <3.12
  - fresnel >=0.13.5
  - cmeutils >=1.3
